services:
  - type: web
    name: test
    env: node
    repo: https://github.com/Mohamed-Hackrs/TokenServer-nodejs/tree/master
    rootDir: .
    buildCommand: npm install
    startCommand: npm start
    plan: free
    envVars:
      - key: APP_ID
        sync: false
      - key: APP_CERTIFICATE
        sync: false
